# Generated by Django 5.2.1 on 2025-05-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dob", models.DateField()),
                (
                    "fitness_program",
                    models.CharField(
                        choices=[
                            ("Yoga", "Yoga"),
                            ("Zumba", "Zumba"),
                            ("Pilates", "Pilates"),
                            ("Weight Training", "Weight Training"),
                            ("CrossFit", "CrossFit"),
                        ],
                        default="Yoga",
                        max_length=20,
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[("Basic", "Basic"), ("Premium", "Premium")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Inactive",
                        max_length=10,
                    ),
                ),
                ("joined", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "fitness_programs",
                    models.CharField(
                        default="Yoga",
                        help_text="Comma-separated list of programs this trainer can lead",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=20,
                    ),
                ),
                ("hired_date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Room 101", "Room 101"),
                            ("Room 102", "Room 102"),
                            ("Room 201", "Room 201"),
                            ("Room 202", "Room 202"),
                            ("Main Hall", "Main Hall"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("payment_method", models.CharField(max_length=50)),
                ("subscription_type", models.CharField(max_length=10)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Gym_App.member"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="assigned_trainer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"status": "Active"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Gym_App.trainer",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fitness_program",
                    models.CharField(
                        choices=[
                            ("Yoga", "Yoga"),
                            ("Zumba", "Zumba"),
                            ("Pilates", "Pilates"),
                            ("Weight Training", "Weight Training"),
                            ("CrossFit", "CrossFit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        limit_choices_to={"status": "Active"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gym_App.trainer",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Gym_App.venue"
                    ),
                ),
            ],
        ),
    ]
